### ISSUE TITLE
Component will not re-render if will receive new props

### ISSUE THREAD

**Issue by aniov** [AlvaroBernalG/react-switchable#3]
Hy there,
If I'm using it in a component that will receive props, the \<State active> from \<Switch> will not change.
Can you check that please?
Thank you.

Here is an example: https://codesandbox.io/s/4z7j6w89kx

**Comment by AlvaroBernalG** [comment]
Hi @aniov,

I am about to do a major refactoring. I am planning, to drop React classes for hooks. Apologies for the response delay.
